[build]
  # Se você não tem comando de build (site 100% estático), deixe em branco ou use "echo 'No build needed'"
  command = ""
  # Pasta que contém o index.html e os arquivos finais que devem ser servidos
  publish = "."

[functions]
  # Pasta onde estão suas Netlify Functions
  directory = "netlify/functions"

# Redirects e rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200